services:
  hyperativaservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: hyperativa-backend
    depends_on:
      - hyperativa-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://hyperativa-db:3306/hyperativa?allowPublicKeyRetrieval=true&useSSL=false
    - SPRING_DATASOURCE_USERNAME=hyperativa
    - SPRING_DATASOURCE_PASSWORD=hyperativa123
    networks:
      - hyperativa-network

  hyperativa-db:
    image: mysql:8.0
    container_name: hyperativa-db
    environment:
      MYSQL_DATABASE: hyperativa
      MYSQL_USER: hyperativa
      MYSQL_PASSWORD: hyperativa123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hyperativa-network

volumes:
  mysql-data:

networks:
  hyperativa-network:
